export const actions = {
    profile: {
        DATA_FETCHING: "PROFILE_DATA_FETCHING",
        DATA_FETCHED: "PROFILE_DATA_FETCHED",
        DATA_EDITED: "PROFILE_DATA_EDITED",
        DATA_DELETED: "PROFILE_DATA_DELETED",
        AVATAR_UPDATED: "PROFILE_AVATAR_UPDATED",
        DATA_ERROR: "PROFILE_DATA_ERROR",
        BLOG_DELETED: "BLOG_DELETE_FROM_PROFILE"
    },
    blogs: {
        DATA_FETCHING: "BLOG_DATA_FETCHING",
        DATA_FETCHED: "BLOG_DATA_FETCHED",
        DATA_EDITED: "BLOG_DATA_EDITED",
        DATA_DELETED: "BLOG_DATA_DELETED",
        AVATAR_UPDATED: "BLOG_AVATAR_UPDATED",
        DATA_ERROR: "BLOG_DATA_ERROR",
        DATA_CREATED: "BLOG_DATA_CREATED",
        BLOG_LIKED: "BLOG_DATA_LIKED"
    }
}